[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.5

[font.normal]
family = "MesloLGL Nerd Font Mono"

[keyboard]
bindings = [
    { mods = "Alt",     key = "Key0",   action = "ResetFontSize" },
    { mods = "Alt",     key = "Equals", action = "IncreaseFontSize" },
    { mods = "Alt",     key = "Minus",  action = "DecreaseFontSize" },
    { mods = "Control", key = "V",      action = "Paste" },
    { mods = "None",    key = "F11",    action = "ToggleFullscreen" },
]

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[window]
opacity = 1.0
