[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.5

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[window]
opacity = 1.0
