[greenclip]
history_file = "$HOME/.cache/greenclip.history"
max_history_length = 50
max_selection_size_bytes = 0
trim_space_from_selection = true
use_primary_selection_as_input = false

blacklisted_applications = [ "Qt Selection Owner for keepassxc" ]
static_history = []

enable_image_support = true
image_cache_directory = "/tmp/greenclip/"